/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_takee_Measure */

#ifndef _Included_com_takee_Measure
#define _Included_com_takee_Measure
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_takee_Measure
 * Method:    open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_takee_Measure_open
  (JNIEnv *, jclass);

/*
 * Class:     com_takee_Measure
 * Method:    ioctlMeasure
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_takee_Measure_ioctlMeasure
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_takee_Measure
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_takee_Measure_close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
